services:
  web:
    container_name: "web"
    build: .
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true

  db:
    container_name: "db"
    image: mariadb:11.4.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workhive
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin:5.2.1
    depends_on:
      - db
    environment:
      PMA_PORT: "3306"
      PMA_HOST: "db"
#      MYSQL_ROOT_PASSWORD: "root"
#      PMA_USER: "app"
#      PMA_PASSWORD: "app"
    ports:
      - 81:80

volumes:
  db_data:
  caddy_data:
  caddy_config: