services:
  web:
    image: php:8.0-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: exemple
      MYSQL_DATABASE: workhive
    ports:
      - "3306:3306"

