-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 14:59:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema workhive
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `workhive`;

-- -----------------------------------------------------
-- Schema workhive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workhive` DEFAULT CHARACTER SET utf8;
USE `workhive`;

-- -----------------------------------------------------
-- Table `workhive`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workhive`.`Users`;

CREATE TABLE IF NOT EXISTS `workhive`.`Users`
(
    `id`         INT                              NULL     DEFAULT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(50)                      NOT NULL,
    `last_name`  VARCHAR(50)                      NOT NULL,
    `photo`      VARCHAR(255)                     NULL     DEFAULT NULL,
    `user_role`  ENUM ('member', 'user', 'admin') NOT NULL DEFAULT 'user',
    `phone`      VARCHAR(15)                      NULL     DEFAULT NULL,
    `email`      VARCHAR(100)                     NOT NULL,
    `password`   VARCHAR(255)                     NOT NULL,
    `status`     ENUM ('active', 'inactive')      NOT NULL DEFAULT 'active',
    `created_at` TIMESTAMP                        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP                        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX (`email` ASC) VISIBLE
);


-- -----------------------------------------------------
-- Table `workhive`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workhive`.`Rooms`;

CREATE TABLE IF NOT EXISTS `workhive`.`Rooms`
(
    `id`          INT                         NULL     DEFAULT NULL AUTO_INCREMENT,
    `name`        VARCHAR(100)                NOT NULL,
    `description` TEXT                        NULL     DEFAULT NULL,
    `photo`       VARCHAR(255)                NULL     DEFAULT NULL,
    `capacity`    INT                         NOT NULL,
    `width`       DECIMAL(5, 2)               NOT NULL,
    `length`      DECIMAL(5, 2)               NOT NULL,
    `status`      ENUM ('active', 'inactive') NOT NULL DEFAULT 'active',
    `created_at`  TIMESTAMP                   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  TIMESTAMP                   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


-- -----------------------------------------------------
-- Table `workhive`.`Equipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workhive`.`Equipments`;

CREATE TABLE IF NOT EXISTS `workhive`.`Equipments`
(
    `id`          INT          NULL     DEFAULT NULL AUTO_INCREMENT,
    `name`        VARCHAR(100) NOT NULL,
    `description` TEXT         NULL     DEFAULT NULL,
    `photo`       VARCHAR(255) NULL     DEFAULT NULL,
    `total_stock` INT          NOT NULL,
    `created_at`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


-- -----------------------------------------------------
-- Table `workhive`.`Equipment_Role_Rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workhive`.`Equipment_Role_Rate`;

CREATE TABLE IF NOT EXISTS `workhive`.`Equipment_Role_Rate`
(
    `id`           INT                              NULL     DEFAULT NULL AUTO_INCREMENT,
    `equipment_id` INT                              NOT NULL,
    `user_role`    ENUM ('member', 'user', 'admin') NOT NULL DEFAULT 'user',
    `hourly_rate`  DECIMAL(10, 2)                   NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX (`equipment_id` ASC, `user_role` ASC) VISIBLE,
    INDEX `fk_equipment_role_rate_equipment_id` (`equipment_id` ASC) VISIBLE,
    CONSTRAINT `fk_equipment_role_rate_equipment_id`
        FOREIGN KEY (`equipment_id`)
            REFERENCES `workhive`.`Equipments` (`id`)
            ON DELETE CASCADE
);


-- -----------------------------------------------------
-- Table `workhive`.`Reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workhive`.`Reservations`;

CREATE TABLE IF NOT EXISTS `workhive`.`Reservations`
(
    `id`         INT                                        NULL     DEFAULT NULL AUTO_INCREMENT,
    `user_id`    INT                                        NOT NULL,
    `room_id`    INT                                        NOT NULL,
    `start_at`   DATETIME                                   NOT NULL,
    `end_at`     DATETIME                                   NOT NULL,
    `status`     ENUM ('pending', 'confirmed', 'cancelled') NOT NULL DEFAULT 'pending',
    `created_at` TIMESTAMP                                  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP                                  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `fk_reservations_user_id` (`user_id` ASC) VISIBLE,
    INDEX `fk_reservations_room_id` (`room_id` ASC) VISIBLE,
    CONSTRAINT `fk_reservations_user_id`
        FOREIGN KEY (`user_id`)
            REFERENCES `workhive`.`Users` (`id`)
            ON DELETE CASCADE,
    CONSTRAINT `fk_reservations_room_id`
        FOREIGN KEY (`room_id`)
            REFERENCES `workhive`.`Rooms` (`id`)
            ON DELETE CASCADE
);


-- -----------------------------------------------------
-- Table `workhive`.`Room_Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workhive`.`Room_Equipment`;

CREATE TABLE IF NOT EXISTS `workhive`.`Room_Equipment`
(
    `id`           INT       NULL     DEFAULT NULL AUTO_INCREMENT,
    `room_id`      INT       NOT NULL,
    `equipment_id` INT       NOT NULL,
    `quantity`     INT       NOT NULL,
    `assigned_at`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `fk_room_equipment_room_id` (`room_id` ASC) VISIBLE,
    INDEX `fk_room_equipment_equipment_id` (`equipment_id` ASC) VISIBLE,
    CONSTRAINT `fk_room_equipment_room_id`
        FOREIGN KEY (`room_id`)
            REFERENCES `workhive`.`Rooms` (`id`)
            ON DELETE CASCADE,
    CONSTRAINT `fk_room_equipment_equipment_id`
        FOREIGN KEY (`equipment_id`)
            REFERENCES `workhive`.`Equipments` (`id`)
            ON DELETE CASCADE
);


-- -----------------------------------------------------
-- Table `workhive`.`Room_Role_Rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workhive`.`Room_Role_Rate`;

CREATE TABLE IF NOT EXISTS `workhive`.`Room_Role_Rate`
(
    `id`          INT                              NULL     DEFAULT NULL AUTO_INCREMENT,
    `room_id`     INT                              NOT NULL,
    `user_role`   ENUM ('member', 'user', 'admin') NOT NULL DEFAULT 'user',
    `hourly_rate` DECIMAL(10, 2)                   NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX (`room_id` ASC, `user_role` ASC) VISIBLE,
    INDEX `fk_room_role_rate_room_id` (`room_id` ASC) VISIBLE,
    CONSTRAINT `fk_room_role_rate_room_id`
        FOREIGN KEY (`room_id`)
            REFERENCES `workhive`.`Rooms` (`id`)
            ON DELETE CASCADE
);


-- -----------------------------------------------------
-- Table `workhive`.`Reservation_Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workhive`.`Reservation_Equipment`;

CREATE TABLE IF NOT EXISTS `workhive`.`Reservation_Equipment`
(
    `id`             INT       NULL     DEFAULT NULL AUTO_INCREMENT,
    `reservation_id` INT       NOT NULL,
    `equipment_id`   INT       NOT NULL,
    `quantity`       INT       NOT NULL,
    `created_at`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `fk_reservation_equipment_reservation_id` (`reservation_id` ASC) VISIBLE,
    INDEX `fk_reservation_equipment_equipment_id` (`equipment_id` ASC) VISIBLE,
    CONSTRAINT `fk_reservation_equipment_reservation_id`
        FOREIGN KEY (`reservation_id`)
            REFERENCES `workhive`.`Reservations` (`id`)
            ON DELETE CASCADE,
    CONSTRAINT `fk_reservation_equipment_equipment_id`
        FOREIGN KEY (`equipment_id`)
            REFERENCES `workhive`.`Equipments` (`id`)
            ON DELETE CASCADE
);


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;



